SELECT
/*交易编码*/
	'' AS TRANSACTIONNO,
/*公司编码*/
	'' AS COMPANYCODE,
	PRPPMAIN.POLICYNO AS POLICYNO,
	PRPPMAIN.ENDORSENO AS ENDORSENO,
	PRPPMAIN.APPLYNO AS APPLYNO,
	PRPPMAIN.RISKCODE AS RISKCODE,
	PRPPHEAD.ENDORTYPE AS ENDORTYPE,
/*批改类型名称*/
	'' AS ENDORTYPENAME,
	PRPPHEAD.REASONTEXT AS ENDORREASON,
/*批改申请时间 YYYY-MM-DD HH:MM:SS*/
	PRPPHEAD.ENDORDATE AS APPLYDATE,
	PRPPHEAD.UNDERWRITEENDDATE AS UWVERDICTDATE,
/*批单生成时间 YYYY-MM-DD HH:MM:SS*/
	PRPPHEAD.VALIDDATE + PRPPHEAD.VALIDHOUR AS ENDORSECREATDATE,
	PRPPMAIN.UWTYPE AS UWPTYPE,
/*批单生效时间 YYYY-MM-DD HH:MM:SS*/
	PRPPHEAD.VALIDDATE AS CERTIEFFECTTIME,
	PRPPMAIN.CURRENCY AS CURRENY,
	PRPPMAIN.CHGSUMAMOUNT AS CHGAMOUNTORIG,
/*保额变化量，CHGSUMAMOUNT转RMB*/
	'' AS CHGAMOUNT,
	PRPPMAIN.CURRENCY AS CURRENYORIG,
	PRPPMAIN.CHGSUMGROSSPREMIUM AS CHGPREMIUMTAXORIG,
/*保费变化量（含税），CHGSUMGROSSPREMIUM转RMB*/
	'' AS CHGPREMIUMTAX,
	PRPPMAIN.CHGNETPREMIUM AS CHGPREMIUMNOTAXORIG,
/*保费变化量（不含税），CHGNETPREMIUM转RMB*/
	'' AS CHGPREMIUMNOTAX,
	PRPPMAIN.CHGSUMVAT AS SUMTAXFEEORIG,
/*税额变化量，CHGSUMVAT转RMB*/
	'' AS SUMTAXFEE,
/*交易完成时间*/
	'' AS TRANSACTIONDATE,
/*批次号*/
	'' AS BATCHNO 
FROM
	PRPPMAIN,
	PRPPHEAD
WHERE
	PRPPMAIN.APPLYNO = PRPPHEAD.APPLYNO