ora_db=$1
user_name=$2
user_pwd=$3
log_file=$4

sqlplus ${user_name}/${user_pwd}@${ora_db}<<!
WHENEVER SQLERROR EXIT SQL.SQLCODE
set timing on;
spool ${log_file}

ALTER SESSION ENABLE PARALLEL DML;

INSERT /*+ append PARALLEL(16) */
INTO MID_PROCGRPAPPNT

SELECT /*+ PARALLEL(16) */

'000000' AS TRANSACTIONNO ,
'000000' AS COMPANYCODE ,
cinsured.POLICYNO AS GRPPOLICYNO ,
'000000' AS GRPPRTNO ,
cinsured.INSUREDCODE AS APPNTNO ,
'000000' AS CUSTOMERNO ,
cinsured.INSUREDNAME AS APPNTNAME ,
cinsured.NATIONCODE AS IHGCODE ,
cinsured.COUNTRY AS COUNTRYCODE ,
cinsured.province AS PROVINCE ,
cinsured.city AS CITY ,
cinsured.region AS COUNTY ,
cinsured.other AS STREET ,
cinsured.postalCode AS POSTCODE ,
cinsured.tagCode AS BUSINESSTYPE ,
cinsured.UNITTYPE AS GRPNATURE ,
'000000' AS BUSILICENSECODE ,
cinsured.BUSILICENSEPERIOD AS BUSILICENSESDATE ,
cinsured.BUSILICENSEPERIOD AS BUSILICENSEEDATE ,
cinsured.TEXIDENTITYNUMBER AS TAXREGISTNO ,
cinsured.ORGANIZATIONCODE AS ORGANIZATIONNO ,
'000000' AS UNIFORMSOCIALCREDIT ,
'000000' AS REGISTMONEYORIGCUR ,
1 AS REGISTMONEYORIG ,
1 AS REGISTMONEY ,
'000000' AS ASSETORIGCUR ,
1 AS ASSETORIG ,
1 AS ASSET ,
1 AS NETPROFITRATE ,
'000000' AS MAINBUSSINESS ,
cinsured.CORPORATIONNAME AS CORPORATION ,
1 AS PEOPLES ,
1 AS ONWORKPEOPLES ,
1 AS OFFWORKPEOPLES ,
'000000' AS BANKCODE ,
cinsured.TAXBUREABANK AS BANKNAME ,
cinsured.TAXBUREAACCOUNT AS BANKACCNO ,
cinsured.postalCode AS ZIPCODE ,
cinsured.FAXNUMBER AS FAX ,
cinsured.MOBILE AS PHONE ,
cinsured.EMAIL AS COMPANYEMAIL ,
cinsured.LINKERNAME AS LINKERNAME ,
cinsured.linkerPhone AS LINKERMOBILE ,
cinsured.linkerPhone AS LINKERNUMBER ,
'1990-01-01' AS FOUNDDATE ,
'000000' AS SOCIETYSTATFLAG ,
'000000' AS SOCIALGRPINSUNO ,
'000000' AS CREDITGRADE ,
'1990-01-01' AS TRANSACTIONDATE ,
'000000' AS BATCHNO 

FROM fccbdb.prpcinsured cinsured
 
commit;

spool off
!
