ora_db=$1
user_name=$2
user_pwd=$3
log_file=$4

sqlplus ${user_name}/${user_pwd}@${ora_db}<<!
WHENEVER SQLERROR EXIT SQL.SQLCODE
set timing on;
spool ${log_file}

ALTER SESSION ENABLE PARALLEL DML;

INSERT /*+ append PARALLEL(16) */
INTO MID_PROCINSURED

SELECT /*+ PARALLEL(16) */

'000000' AS TRANSACTIONNO ,
'000000' AS COMPANYCODE ,
cinsured.POLICYNO AS POLICYNO ,
cinsured.INSUREDCODE AS INSUREDNO ,
cinsured.RELATIONTOINSURED AS RELATIONTOMAININSURED ,
'000000' AS ISMAININSUREDFLAG ,
cinsured.mainInsuredFlag AS MAININSUREDNO ,
'000000' AS GROUPNO ,
cinsured.RELATIONTOAPPNT AS RELATIONTOAPPNT ,
cinsured.INSUREDNAME AS INSUREDNAME ,
cinsured.INSUREDENAME AS INSUREDENAME ,
cinsured.SEX AS INSUREDSEX ,
cinsured.AGE AS INSUREDAGE ,
cinsured.BIRTHDAY AS INSUREDBIRTHDATE ,
cinsured.identifyType AS INSUREDIDENTIFYTYPE ,
cinsured.IDENTIFYNUMBER AS INSUREDIDENTIFYNUMBER ,
'000000' AS APPLIRESIDENCE ,
'000000' AS RGTADDRESS ,
cinsured.nation AS NATIONALITY ,
cinsured.NATIONCODE AS IHGCODE ,
cinsured.COUNTRY AS NATIVEPLACE ,
cinsured.province AS PROVINCE ,
cinsured.city AS CITY ,
cinsured.region AS COUNTY ,
cinsured.other AS INSUREDADDRESS ,
cinsured.postalCode AS POSTCODE ,
1 AS STATURE ,
1 AS AVOIRDUPOIS ,
'000000' AS SALARYORIGCUR ,
1 AS SALARYORIG ,
1 AS SALARY ,
cinsured.MARRIAGE AS MARRIAGE ,
'1990-01-01' AS MARRIAGEDATE ,
'000000' AS INSUREDMOBILE ,
cinsured.HOMEPHONE AS INSUREDPHONENUMBER ,
cinsured.FAXNUMBER AS INSUREDFAXNUMBER ,
cinsured.EMAIL AS INSUREDEMAIL ,
cinsured.LINKERADDRESS AS INSUREDPOSTADDRESS ,
cinsured.LINKERPOSTCODE AS INSUREDPOSTCODE ,
'000000' AS DEGREE ,
'000000' AS POSITION ,
'000000' AS OCCUPATIONTYPE ,
'000000' AS OCCUPATIONNAME ,
cinsured.OCCUPATIONCODE AS OCCUPATIONCODE ,
'000000' AS OCCUPATIONCODENAME ,
'000000' AS WORKTYPE ,
'000000' AS PLURALITYTYPE ,
'1990-01-01' AS DEATHDATE ,
'000000' AS SMOKEFLAG ,
'000000' AS GRPNAME ,
'000000' AS LICENSEFLAG ,
'000000' AS LICENSETYPE ,
'000000' AS SOCIALINSUFLAG ,
'000000' AS SOCIALINSUNO ,
'000000' AS ARRIVECITY ,
'000000' AS ABNORMALFLAG ,
'000000' AS ABNORMALCONTENT ,
'000000' AS CUSTOMERNO ,
'000000' AS CREDITGRADE ,
'1990-01-01' AS TRANSACTIONDATE ,
'000000' AS BATCHNO 

FROM fccbdb.prpcinsured cinsured
 
commit;

spool off
!
