ora_db=$1
user_name=$2
user_pwd=$3
log_file=$4

sqlplus ${user_name}/${user_pwd}@${ora_db}<<!
WHENEVER SQLERROR EXIT SQL.SQLCODE
set timing on;
spool ${log_file}

ALTER SESSION ENABLE PARALLEL DML;

INSERT /*+ append PARALLEL(16) */
INTO MID_PROCGRPINSURED

SELECT /*+ PARALLEL(16) */

'000000' AS TRANSACTIONNO ,
'000000' AS COMPANYCODE ,
cinsured.POLICYNO AS POLICYNO ,
cinsured.INSUREDCODE AS ASSUREDNO ,
cinsured.INSUREDNAME AS ASSUREDNAME ,
null AS IHGCODE ,
cinsured.COUNTRY AS COUNTRYCODE ,
cinsured.province AS PROVINCE ,
cinsured.city AS CITY ,
cinsured.region AS COUNTY ,
null AS STREET ,
cinsured.postalCode AS POSTCODE ,
null AS BUSINESSTYPE ,
cinsured.UNITTYPE AS GRPNATURE ,
null AS BUSILICENSECODE ,
null AS BUSILICENSESDATE ,
null AS BUSILICENSEEDATE ,
cinsured.TEXIDENTITYNUMBER AS TAXREGISTNO ,
cinsured.ORGANIZATIONCODE AS ORGANIZATIONNO ,
null AS UNIFORMSOCIALCREDIT ,
null AS REGISTMONEYORIGCUR ,
null AS REGISTMONEYORIG ,
null AS REGISTMONEY ,
null AS ASSETORIGCUR ,
null AS ASSETORIG ,
null AS ASSET ,
null AS NETPROFITRATE ,
null AS MAINBUSSINESS ,
cinsured.CORPORATIONNAME AS CORPORATION ,
null AS PEOPLES ,
null AS ONWORKPEOPLES ,
null AS OFFWORKPEOPLES ,
null AS ZIPCODE ,
null AS FAX ,
null AS PHONE ,
null AS COMPANYEMAIL ,
cinsured.LINKERNAME AS LINKERNAME ,
null AS LINKERMOBILE ,
cinsured.linkerPhone AS LINKERNUMBER ,
null AS FOUNDDATE ,
null AS CUSTOMERNO ,
null AS CREDITGRADE ,
'1990-01-01' AS TRANSACTIONDATE ,
'000000' AS BATCHNO 

FROM fccbdb.prpcinsured cinsured
 
commit;

spool off
!
