ora_db=$1
user_name=$2
user_pwd=$3
log_file=$4

sqlplus ${user_name}/${user_pwd}@${ora_db}<<!
WHENEVER SQLERROR EXIT SQL.SQLCODE
set timing on;
spool ${log_file}

ALTER SESSION ENABLE PARALLEL DML;

INSERT /*+ append PARALLEL(16) */
INTO MID_PROCPLAN

SELECT /*+ PARALLEL(16) */

'000000' AS TRANSACTIONNO ,
'000000' AS COMPANYCODE ,
cplan.POLICYNO AS POLICYNO ,
1 AS FEESERIALNO ,
cplan.EXCHANGENO AS EXCHANGENO ,
cplan.PAYNO AS PAYNO ,
cplan.PAYREASON AS PAYREASON ,
cplan.CURRENCY AS CURRENCY ,
cplan.PLANFEE AS PLANFEE ,
cplan.PLANFEE*cplan.PAYRATE AS PLANFEERMB ,
cplan.PAYTYPE AS PAYTYPE ,
cplan.PLANSTARTDATE AS PLANDATE ,
cplan.PLANENDDATE AS PLANPAYDATE ,
1 AS SUBSIDYRATE ,
1 AS SUBSIDYAMOUNT ,
null AS REPERIOD ,
'1990-01-01' AS TRANSACTIONDATE ,
'000000' AS BATCHNO 

FROM fccbdb.prpcplan cplan
 
commit;

spool off
!
