SELECT 
	'' AS TRANSACTIONNO,-- 暂不映射
	'' AS COMPANYCODE,-- 暂不映射
	AS POLICYNO,
	AS REGISTNO,
	AS CLMNO,
	AS CASENO,
	AS RECEIPTNO,
	AS COSTITEMCODE,
	AS COSTITEMNAME,
	AS CLAIMANTNO,
	AS CUSTOMERNO,
	AS LOSSNAME,
	AS LOSSSEX,
	AS LOSSBIRTHDATE,
	AS LOSSIDENTIFYTYPE,
	AS LOSSIDENTIFYNO,
	AS FEEAMOUNT,
	AS FEEDEDUCTIBLEAMOUNT,
	'' AS TRANSACTIONDATE,-- 暂不映射
	'' AS BATCHNO-- 暂不映射
FROM 
	-- 表关联尚不清楚

	