SELECT
	'' AS TRANSACTIONNO,-- 暂不映射
	'' AS COMPANYCODE,-- 暂不映射
	AS POLICYNO,
	AS REGISTNO,
	AS CLMNO,
	AS CASENO,
	AS RECEIPTNO,
	AS COSTITEMCODE,
	AS COSTITEMNAME,
	AS COSTCATEGORY,
	AS MEDICALDETAILNAME,
	AS MEDICALCHEMISTRYNAME,
	AS MEDICALDETAILPY,
	AS MEDICALDETAILWB,
	AS CHARGEITEMLEVELCODE,
	AS FEEAMOUNT,
	AS FEEDEDUCTIBLEAMOUNT,
	AS MEDICALQUANTITY,
	AS UNITPRICE,
	AS UNIT,
	'' AS TRANSACTIONDATE,-- 暂不映射
	'' AS BATCHNO-- 暂不映射
FROM
	-- 表关联尚不清楚

