SELECT
    NULL AS TRANSACTIONNO,
    NULL AS COMPANYCODE,
    MA.POLICYNO AS POLICYNO	,
    MA.RISKCODE AS RISKCODE,
    COM.CURRENCY AS CURRENCY,
    COM.COSTFEE AS SUMCOSTFEE,
    COM.COSTRATE AS POLICYCOSTRATE,
    NULL AS TRANSACTIONDATE,
    NULL AS BATCHNO
FROM FCCBDB.PRPCCOMMISSION COM
    LEFT JOIN PRPCMAIN MA ON MA.ID = COM.MAINID