SELECT
    NULL AS TRANSACTIONNO,
    NULL AS COMPANYCODE,
    PLR.POLICYNO AS POLICYNO,
    PLR.REGISTNO AS REGISTNO,
    PLR.CANCELREASON AS REGISTDEALTYPECODE,
    PLR.REPORTTIME AS DEALTIME,
	-- 通过关联码表转换
    CASE WHEN PLR.CANCELREASON = '03' THEN '03'
    ELSE PLR.CANCELREASON
    END AS NOCLAIMREASON,
	-- 条件必填未找到字段
    CASE WHEN PLR.CANCELREASON = '04' THEN '1900-01-01 00:00:00'
    ELSE ''
    END AS REGISTCANCELRECOVERDATE,
	-- 条件必填未找到字段
    CASE WHEN PLR.CANCELREASON = '04' THEN '9999999999'
    ELSE ''
    END AS REGISTCANCELRECOVERNO,
    PLR.MAKECOME AS ACCEPTANCECODE,
    '' AS ACCEPTANCENAME,
    NULL AS TRANSACTIONDATE, 
    NULL AS BATCHNO 
FROM
	INS_CLAIM.PRPLREGIST PLR