SELECT
	NULL AS TRANSACTIONNO,
	NULL AS COMPANYCODE,
	CLA.POLICYNO AS POLICYNO,
	CLA.REGISTNO AS REGISTNO,
	CLA.CLAIMNO AS CLMNO,
	CLA.CASENO AS CASENO,
	CHA.COMPENSATENO AS COMPENSATENO,
	--  º¯ÊýËãÐòºÅ,oracle·Å¿ª
	-- 	ROW_NUMBER() OVER(PARTITION BY CHA.COMPENSATENO ORDER BY CHA.COMPENSATENO) AS SERIALNO,
	'' AS ITEMKINDNO,
	-- Î´ÕÒµ½×Ö¶Î
	'000000' AS CLAIMEXPFLAG,
	CHA.CHARGECODE AS FEETYPECODE,
	CHA.CHARGENAME AS FEETYPENAME,
	CHA.CURRENCY AS CURRENCY,
	CHA.FEEAMT AS EXPAMOUNT,
	CHA.EXCHRATE AS EXCHANGE,
	CHA.FEEAMT*CHA.EXCHRATE AS EXPAMOUNTCNY,
	CASE AG.AGENCYTYPE WHEN '01' THEN AG.AGENCYCODE
	ELSE ''
	END AS ADJUSTERCODE,
	CASE AG.AGENCYTYPE WHEN '01' THEN AG.AGENCYNAME
	ELSE ''
	END AS ADJUSTERNAME,
	NULL AS TRANSACTIONDATE,
	NULL AS BATCHNO
FROM
	INS_CLAIM.PRPLCHARGE CHA,
	INS_CLAIM.PRPLCLAIM CLA,
	INS_CLAIM.PRPLCOMPENSATE COM,
	INS_CLAIM.PRPLREGIST REG,
	INS_CLAIM.PRPLAGENCY AG
WHERE
	CLA.CLAIMNO = COM.COMPENSATENO
	AND CHA.COMPENSATENO = COM.COMPENSATENO
	AND CLA.REGISTNO = REG.REGISTNO
	AND AG.REGISTNO = CLA.REGISTNO