SELECT
	PC.POLICYNO AS POLICYNO,
	PC.REGISTNO AS REGISTNO,
	PC.CLAIMNO AS CLMNO,
	PC.CASENO AS CASENO,
	PLC.COMPENSATENO AS COMPENSATENO,
	PLLP.ITEMKINDNO AS ITEMKINDNO,
	-- SERIALNO是将PLLPF.COMPENSATENO分组后编号获取,oracle使用
	-- ROW_NUMBER() OVER(PARTITION BY PLLPF.COMPENSATENO ORDER BY PLLPF.COMPENSATENO) AS SERIALNO，
-- 	-- ROW_NUMBER() OVER(PARTITION BY PLLPF.COMPENSATENO ORDER BY PLLPF.COMPENSATENO) AS EMPNO，
	PLLP.RISKCODE AS RISKCODE,
	PLLP.CLAUSECODE AS CLAUSECODE,
	PLLP.KINDCODE AS KINDCODE,
	NULL AS ONELOSSCODE,
	NULL AS ONELOSSNAME,
	NULL AS TWOLOSSCODE,
	NULL AS TWOLOSSNAME,
	NULL AS THREELOSSCODE,
	NULL AS THREELOSSNAME,
	NULL AS FOURLOSSCODE,
	NULL AS FOURLOSSNAME,
	PC.DAMAGECODE AS OCCREASONCODE,
	PC.DAMAGENAME AS OCCREASONNAME,
	PLLP.PERSONNAME AS EMPNAME,
	PLLP.PERSONSEX AS SEX,
	PLLP.PERSONAGE AS AGE,
	PLLP.CERTITYPE AS CERTTYPE,
	PLLP.CERTICODE AS CERTNO,
	PLLP.DUTYRATE AS INDEMNITYDUTYRATE,
	PLLP.CURRENCY AS DEDUCTIBLEORIGCUR,
	PLLP.DEDUCTABSAMT AS DEDUCTIBLEORIG,
	PLLP.DEDUCTABSAMT AS DEDUCTIBLE,
	PLLP.DEDUCTADDRATE AS DEDUCTIBLERATE,
	PLLPF.FORMULA AS UNITCOMPENSATEEXP,
	PLLP.CURRENCY AS STANDPAYORIGCUR,
	PLLP.SUMREALPAY AS STANDPAYORIG,
	PLLP.SUMREALPAY * PLLP.EXCHRATE AS STANDPAY,
	PLLP.CURRENCY AS CURRENCY,
	PLLP.OFFPREAMT AS UNITSUMPREPAIDORIG,
	PLLP.OFFPREAMT * PLLP.EXCHRATE AS UNITSUMPREPAID,
	PLLP.CURRENCY AS UNITSUMREALPAYORIGCUR,
	PLLP.SUMREALPAY AS UNITSUMREALPAYORIG,
	PLLP.SUMREALPAY * PLLP.EXCHRATE AS UNITSUMREALPAY,
	PLLP.CURRENCY AS UNITEXCEPTDEDUCTIBEORIGCUR,
	PLLP.DEDUCTOFFAMT AS UNITEXCEPTDEDUCTIBEORIG,
	PLLP.DEDUCTOFFAMT * PLLP.EXCHRATE AS UNITEXCEPTDEDUCTIBE,
	PLC.UNDERWRITEDATE AS UNDERWRITEENDDATE,
	PLC.PAYSTATUS AS PFSTATUS,
	PC.RELATERECOVERY AS RECOVERYFLAG,
	PLC.LAWSUITFLAG AS LAWSUITFLAG,
	'' AS LAWSUITNO,
	-- 理赔结论代码必填但未找到字段
	'000000' AS GIVETYPE,
	-- 取的字段为：备注（理算意见），还是按照GIVETYPE字段进行码表转换
	PLC.REMARK AS GIVETYPEDESCRIPTION,
	-- 条件必填，未找到字段
	'' AS REFUSEPAYRCODE,
	-- 条件必填，未找到字段
	'' AS GETDUTYKIND,
	'' AS LOSSFEETYPE,
	-- 条件必填，未找到字段，且由赔付责任类型字段（该字段未找到）判断，
	'' AS CRITICALILLNESSCODE,
	-- 条件必填
	PLLPF.CLAIMRATE AS CLAIMRATE,
	-- 条件必填
	'' AS CLAIMRATIOEND,
	PLC.COMCODE AS UNDERWRITECOMCODE,
	-- 由COMCODE字段配合码表转换
	'' AS UNDERWRITECOMNAME,
	NULL AS TRANSACTIONDATE,
	NULL AS BATCHNO 
FROM
	INS_CLAIM.PRPLCLAIM PC,
	INS_CLAIM.PRPLCOMPENSATE PLC,
	INS_CLAIM.PRPLLOSSPERSON PLLP,
	INS_CLAIM.PRPLLOSSPERSONFEE PLLPF 
WHERE
	PC.CLAIMNO = PLC.CLAIMNO 
	AND PLC.COMPENSATENO = PLLP.COMPENSATENO 
	AND PLLP.COMPENSATENO = PLLPF.COMPENSATENO 
	AND PLC.COMPENSATENO = PLLPF.COMPENSATENO