SELECT
    NULL AS TRANSACTIONNO,
    NULL AS COMPANYCODE,
    COM.POLICYNO AS POLICYNO,
    INFO.REGISTNO AS REGISTNO,
    COM.CLAIMNO AS CLMNO,
    COM.CASENO AS CASENO,
    -- 	ROW_NUMBER() OVER(PARTITION BY INFO.COMPENSATENO ORDER BY INFO.ID) AS BNFNO,
    NULL AS IHGCODE,
    NULL AS COUNTRYCODE,
    NULL AS PROVINCE,
    NULL AS CITY,
    NULL AS COUNTY,
    NULL AS DETAILADD,
    NULL AS POSTCODE,
    BEN.BENEFITORDER AS BNFGRADE,
    PAY.CERTIFYTYPE AS IDTYPE,
    PAY.CERTIFYNO AS IDNO,
    BEN.PAYEERALATIONSHIP AS RELATIONTOINSURED,
    COM.INSUREDCODE AS INSUREDNO,
    BEN.BENEFITRATE AS BNFLOT,
    INFO.SUMREALPAY AS GETMONEY,
    '' AS CASEGETMODE,
    '' AS CASEPAYMODE,
    -- 下面四个字段支付方式为银行卡或银行类转账必填，现无字段判断
    '000000' AS BANKCODE,
    PAY.BANKNAME AS BANKNAME,
    PAY.PAYEENAME AS  ACCNAME,
    PAY.ACCOUNTNO AS  BANKACCNO,
    NULL AS CUSTOMERNO,
    NULL AS TRANSACTIONDATE,
    NULL AS BATCHNO
FROM INS_CLAIM.PRPLBENEFICIARY BEN
    LEFT JOIN INS_CLAIM.PRPLCLAIM CLA ON BEN.REGISTNO = CLA.REGISTNO
    LEFT JOIN INS_CLAIM.PRPLCOMPENSATE COM ON COM.REGISTNO = CLA.REGISTNO
    LEFT JOIN INS_CLAIM.PRPLPAYPERSON PAY ON PAY.REGISTNO = COM.REGISTNO
    LEFT JOIN INS_CLAIM.PRPLPAYEEINFO INFO ON INFO.PAYEEID = PAY.ID