ora_db=$1
user_name=$2
user_pwd=$3
log_file=$4

sqlplus ${user_name}/${user_pwd}@${ora_db}<<!
WHENEVER SQLERROR EXIT SQL.SQLCODE
set timing on;
spool ${log_file}

ALTER SESSION ENABLE PARALLEL DML;

INSERT /*+ append PARALLEL(16) */
INTO MID_ProCMain

select 
'000000' as TRANSACTIONNO ,
'000000' as COMPANYCODE ,
prpcm.POLICYNO as POLICYNO ,
prpcm.proposalno as PROPOSALNO ,
prpcm.RENEWALNO as RENEWPOLICYNO ,
prpcm.RISKCODE as RISKCODE ,
null as SERIALNO ,
prpcm.POLICYSORT as POLICYSORT ,
prpcm.BUSINESSFLAG as BUSINESSNATURE ,
prpcm.LANGUAGE as LANGUAGE ,
prpcm.POLICYTYPE as POLICYTYPE ,
prpcm.STARTDATE as STARTTIME ,
prpcm.ENDDATE as ENDTIME ,
prpcm.SIGNDATE as SIGNDATE ,
prpcm.INPUTTIME as OPERATEDATE ,
prpcm.UNDERWRITEENDDATE as UWCONCLUEDATE ,
case prpcm.UNDERWRITEFLAG when '1' then '01' else '02' end as UWCONCLUE ,
null as RSUWCONCLUE ,
prpcm.UNDERWRITEFLAG  as UWCONCLUEDES ,
prpcm.UNDERWRITEENDDATE as POLICYCREATDATE ,
prpcm.ENDDATE as POLICYENDDATE ,
prpph.ReasonCode as TERMINATIONREASON ,
null as CURRENCY ,
null as SUMINVESTORIG ,
null as SUMINVESTMENT ,
null as SUMVALUEORIGCUR ,
null as SUMVALUEORIG ,
null as SUMVALUE ,
null as SURRENDERAMOUNTORIGCUR ,
null as SURRENDERAMOUNTORIG ,
null as SURRENDERAMOUNT ,
prpcm.CURRENCY as SUMAMOUNTORIGCUR ,
prpcm.SUMAMOUNT as SUMAMOUNTORIG ,
prpcm.sumAmount1 as SUMAMOUNT ,
prpcm.CURRENCY as SUMTAXPREMIUMORIGCUR ,
prpcm.SUMPREMIUM as SUMTAXPREMIUMORIG ,
prpcm.SUMPREMIUM as SUMPREMIUM ,
prpcm.CURRENCY as SUMNETPREMIUMORIGCUR ,
prpcm.SUMPREMIUM-prpcm.SUMVAT as SUMNETPREMIUMORIG ,
prpcm.SUMPREMIUM-prpcm.SUMVAT as SUMNETPREMIUM ,
prpcm.CURRENCY as SUMACCPREMORIGCUR ,
null as SUMACCPREMORIG ,
null as SUMACCPREM ,
prpcm.CURRENCY as SUMTAXFEEORIGCUR ,
prpcm.SUMVAT as SUMTAXFEEORIG ,
prpcm.sumVat1 as SUMTAXFEE ,
prpcm.SUMPREMIUM / prpcm.sumAmount1 as RATE ,
prpcm.CURRENCY as SUMSUBPREMORIGCUR ,
prpcm.SUMSUBPREM as SUMSUBPREMORIG ,
prpcm.SUMSUBPREM as SUMSUBPREM ,
null as SUMQUANTITY ,
null as AUTOTRANSRENEWFLAG ,
prpcm.PAYTIMES as PAYTIMES ,
prpcm.UNDERWRITEFLAG as UWTYPE ,
prpcm.CoinsFlag as COINSFLAG ,
prpcm.CROSSFLAG as CROSSFLAG ,
null as AGENTTYPE ,
prpcm.REINSFLAG as REINSFLAG ,
prpcm.ALLINSFLAG as ALLINSFLAG ,
null as FAMILYFLAG ,
null as POLICYFLAG ,
prpcm.paytype as PAYMODE ,
prpcm.JUDICALSCOPE as JUDICALSCOPE ,
prpcm.AREACODE as EFFPREFECTURECODE ,
null as BENEFITTYPE ,
prpcm.MAKECOM as MAKECOM ,
prpcm.OPERATESITE as OPERATESITE ,
prpcm.COMCODE as COMCODE ,
prpcm.COMNAME as COMNAME ,
prpcm.COMCODE as CIRCPOPEDOMCODE ,
prpcm.COMNAME as CIRCPOPEDOMNAME ,
prpcm.AGRIFLAG as AGRICULTUREFLAG ,
prpcm.ARGUESOLUTION as RESOLUTIONCODE ,
prpcm.JfeeFlag as PAYFLAG ,
prpcm.RENEWALFLAG  as RENEWFLAG ,
null as ANONYMOUSFLAG ,
prpcm.SUMQUANTITY as COPIES ,
null as HESITATIONENDDATE ,
null as BILLINGRATE ,
null as SPECIFICBUSINESSFLAG ,
null as SPECIFICBUSINESSCODE ,
null as THIRDNAME ,
null as BUSILICENSECODE ,
null as TAXREGISTNO ,
null as ORGANIZATIONNO ,
null as UNIFORMSOCIALCREDIT ,
'000000' as TRANSACTIONDATE ,
'000000' as BATCHNO

from fccbdb.prpcmain prpcm left join fccbdb.prpphead prpph on prpcm.PolicyNo = prpph.PolicyNo


commit;

spool off
!